name: ntodotxt

description: App for managing your todos within a todo.txt file locally or via webdav (e.g. Nextcloud)
publish_to: 'none'  # Remove this line if you wish to publish to pub.dev
version: 0.12.1+27

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.2
  crypto: ^3.0.3
  cupertino_icons: ^1.0.6
  dio: ^5.1.0
  equatable: ^2.0.5
  file_picker: ^6.1.1
  flex_color_scheme: ^7.3.1
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^9.0.0
  go_router: ^13.0.1
  logging: ^1.2.0
  path: ^1.8.3
  path_provider: ^2.0.11
  permission_handler: ^11.3.0
  rxdart: ^0.27.7
  sqflite_common_ffi: ^2.3.1
  sqlite3_flutter_libs: ^0.5.18
  url_launcher: ^6.2.1
  webdav_client: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  file: ^7.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_oss_licenses: ^2.0.1
  test_cov_console: ^0.2.2

flutter_launcher_icons:
  android: true
  image_path: assets/icon/icon.png
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-VariableFont_wdth,wght.ttf
        - asset: fonts/OpenSans-Italic-VariableFont_wdth,wght.ttf
