---

name: ntodotxt
description: Todo.txt app for managing your todo.txt file stored in Nextcloud.

publish_to: 'none'  # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.2
  equatable: ^2.0.5
  flex_color_scheme: ^7.3.1
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^9.0.0
  go_router: ^11.0.0
  logging: ^1.2.0
  path_provider: ^2.0.11
  rxdart: ^0.27.7
  shared_preferences: ^2.2.1
  url_launcher: ^6.2.1
  webdav_client: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  file: ^7.0.0
  flutter_lints: ^2.0.0
  flutter_oss_licenses: ^2.0.1
  test_cov_console: ^0.2.2

flutter:
  uses-material-design: true
